### ISSUE TITLE
Empty gpg fingerprint vars are incorrectly passing validation

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1855]
# Bug

## Description

Skipping on inclusion of the GPG fingerprints variables in the `install_files/ansbile-base/groups/all/site-specific` file and via the `configure` script improperly passes the validation role. When these two variables are missing the validation role should fail.

## Steps to Reproduce

From within `Tails 3.0`:

- Ensure `./securedrop-admin setup` has already been run
- Run `./securedrop-admin sdconfig` - when prompted for fingerprints, just hit `[enter]` to leave them blank.

## Expected Behavior

The `./securedrop-admin sdconfig` script should fail and throw an error. Not having a GPG fingerprint specified would cause the installation to fail further down the chain.

## Actual Behavior

The script passes :man_shrugging: 

## Comments

I have a working fix. Super easy-peasy. On `install_files/ansible-base/roles/validate/tasks/main.yml` line `11` and `14` add the following changes (we are feeding in a `default` filter in case `ossec_gpg_fpr` and `securedrop_app_gpg_fingerprint` dont already exist ) :

```
---
#This role is to check that development and staging defaults gpg info and
#credentials are not used when running the app and mon playbooks for
#production.

- include: validate_users.yml

- include: validate_gpg_info.yml
  with_items:
    - keyfile: "{{ ossec_alert_gpg_public_key }}"
      fingerprint: "{{ ossec_gpg_fpr | default('') }}"

    - keyfile: "{{ securedrop_app_gpg_public_key }}"
      fingerprint: "{{ securedrop_app_gpg_fingerprint | default('') }}"

- include: validate_ossec_info.yml

- include: validate_tails_environment.yml
  when: securedrop_validate_tails_environment
```
