### ISSUE TITLE
Automate gathering app/mon IP addresses and hostnames

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3603]
## Description

Reporting this here while documenting TODOs (#724).

From `install_files/ansible-base/prod-specific.yml`:

```yaml
# TODO Should use ansible to gather this info
monitor_ip: ""
monitor_hostname: ""
app_hostname: ""
app_ip: ""
```
