### ISSUE TITLE
Remove deprecated ansible task that cleans up bashrc tmux additions

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3609]
## Description

Reporting this here while documenting TODOs (#724).

From `install_files/ansible-base/roles/common/tasks/create_users.yml`:

```yaml
# TODO: Backwards-compatibility. Previously, the SecureDrop bashrc additions
# for forcing a terminal multiplexer during interactive login sessions were
# added to ~/.bashrc for each admin user account. It's cleaner to add the
# config lines to /etc/profile.d, so all accounts get them by default.
# Post 0.4, we can remove this task, which is here to clean up the local
# bashrc files so that the additions are only sourced once.
- name: Clean up local bashrc config for admin accounts.
  lineinfile:
    dest: /home/{{ item }}/.bashrc
    line: '. /etc/bashrc.securedrop_additions'
    state: absent
  with_items: "{{ ssh_users }}"
  tags:
    - users
    - environment
```
