### ISSUE TITLE
Improve idempotence of ansible playbooks w.r.t. apache logging

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3614]
## Description

Reporting this here while documenting TODOs (#724).

From `install_files/ansible-base/roles/app-test/tasks/staging_wsgi_files.yml`:

```yaml
# TODO: This staging-only template clobbers the production template
# installed by the `app` role. That means the app-staging host
# will always mark the task as changed. It would be cleaner to merge
# the templates and use group_vars to conditionally enable the logging
# for staging, defaulting to no logging for safety.
- name: Enable logging for Source Interface.
  copy:
    src: source.wsgi.logging
    dest: /var/www/source.wsgi
    owner: "{{ apache_user }}"
    mode: "0640"
  tags:
    - apache
```
