### ISSUE TITLE
Installing `gettext` from Xenial repos is dangerous and can break the sytem

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3636]
## Description

If the playbook breaks during `install_files/ansible-base/roles/app-test/tasks/modern_gettext.yml` and has not yet removed the xenial apt repo, the next run of the playbook will get things horribly out of sync, possibly destroy a system.

## Steps to Reproduce

Change `install_files/ansible-base/roles/app-test/tasks/modern_gettext.yml` to this:

```yaml
---
#
# This can be removed when VM against which this is run are more
# recent than trusty
#
- name: Add gettext xenial apt repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu/ xenial main
    state: present
    update_cache: yes 
  tags:
    - apt

- name: Install modern gettext
  apt:
    name: gettext
    state: latest
  tags:
    - apt

- fail:
    msg: "I am dead"

- name: Remove gettext xenial apt repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu/ xenial main
    state: absent
    update_cache: yes 
  tags:
    - apt
```

Then re-run the playbook. Watch the sadness.

## Expected Behavior

The playbook failing midway through should not ruin the system.

## Actual Behavior

It does.

## Comments

Add a conditional to prevent this from erroring out until after the the apt repo has been removed. But really this is dangerous and we shouldn't be doing it because a `ctrl-C` in the middle wouldn't let the clean up task run and that's Very Bad.
