### ISSUE TITLE
[xenial] Xenial OS installer does not include some required packages if only "OpenSSH Server" selected

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4109]
## Description

During the Xenial OS install, the user is prompted to select software for installation. Under Trusty, SecureDrop required that only `OpenSSH server` be selected. Xenial differs in having a preselected `standard system utilities` option. 

If the user deselects `standard system utilities`, selects `OpenSSH server`, and proceeds with the installation, `./securedrop-admin install` fails at the Gathering Facts step, claiming that it can't connect via SSH.

However, the issue is not with SSH, but with the fact that python is not installed on Xenial with the above software selection choices. (To prove this, turn on -vvvv logging in ansible, grab the SSH command run by gather_facts, and run it at the console.)

It turns out that 3 packages are required to complete the installation, `python`, `apt-transport-https`, and `dnsutils`.

## Steps to Reproduce
(Tested on 5-series NUCs)
- Proceed with a Xenial SecureDrop installation, deselecting standard system utilities and selecting OpenSSH server at the Software Selection dialog

## Expected Behavior
Installation finishes without error

## Actual Behavior
Installation fails during `./securedrop-admin install` as described above

## Comments
Selecting `standard system utilities` may solve this issue, but it also installs unnecessary packages, which is bad.
Installing the packages on the servers manually adds more complexity to the installation procedure, also bad.
One alternative is to install the required packages via a preliminary playbook that disables gather_facts and runs a raw ssh command:
```
#!/usr/bin/env ansible-playbook
---
- name Install required packages on SecureDrop servers
  hosts: securedrop
  any_errors_fatal: yes
  gather_facts: no
  become: yes
  pre_tasks:
    - name: 'install packages'
      raw: 'sudo apt-get -y install python apt-transport-https dnsutils'

```
(Thanks to @kushaldas for this suggestion)

This can be run at the command line, but a proper fix would probably be to add it to the securedrop-admin install function,  just before the main `securedrop-prod.yml` is run. (One downside is that the user would be prompted for the server sudo password twice.)
