### ISSUE TITLE
resolve Ansible deprecation warnings due to using jinja tests with the filter syntax

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4385]
## Description

We're getting Ansible deprecation warnings due to:

```
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|failed` use `result is failed`. 
```

An example task this is occurring on is [here](https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/grsecurity/tasks/clean_packages.yml#L27):

```
- name: Validate that all installed kernels are grsecurity-hardened.
  assert:
    that:
      - item | search('-grsec')
    msg: "Not all non-grsec kernels have been removed, run dpkg-query -W 'linux-image*' for more details."
  with_items: "{{ apt_installed_kernels.stdout_lines }}"
  tags:
    - apt
```

where `item | search('-grsec')` should be updated to `item is search('-grsec')`

The implementer of this ticket should check out the following references and update all relevant tasks to suppress this deprecation warning (all deprecation warnings can be seen in this [build output](https://circleci.com/gh/freedomofpress/securedrop/26352)):
- https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#jinja-tests-used-as-filters
- https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#testing-strings
- https://github.com/ansible/ansible/issues/37370
