### ISSUE TITLE
typed-ast dependency is not pinned

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6411]
## Description

In deb-tests and staging-test-with-rebase, CI is failing with:

```
Creating Python 3 virtualenv in .venv
created virtual environment CPython3.7.13.final.0-64 in 494ms
  creator CPython3Posix(dest=/home/circleci/project/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/circleci/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==60.10.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typed-ast<1.5,>=1.4.0 from https://files.pythonhosted.org/packages/65/b3/573d2f1fecbbe8f82a8d08172e938c247f99abe1be3bef3da2efaa3810bf/typed_ast-1.4.3-cp37-cp37m-manylinux1_x86_64.whl#sha256=5feca99c17af94057417d744607b82dd0a664fd5e4ca98061480fd8b14b18d04 (from astroid==2.5.2->-r securedrop/requirements/python3/develop-requirements.txt (line 48))
make: *** [Makefile:334: ci-deb-tests] Error 1
```

I think this might be fallout from my mypy changes? unclear why it didn't get pinned...

* https://app.circleci.com/pipelines/github/freedomofpress/securedrop/4015/workflows/ad0c7371-c384-4195-b01a-599477924281/jobs/61226
* https://app.circleci.com/pipelines/github/freedomofpress/securedrop/4021/workflows/38c92e91-360e-4b02-95d8-4ef75b4a3377/jobs/61243

**Comment by legoktm** [comment]
The actual dependency is:
```
typed-ast>=1.4.0,<1.5;implementation_name== "cpython" and python_version<"3.8"
```

So because the dev container is on 3.8, it is skipped and doesn't get pinned. Except in some cases, CI is still using 3.7??

```
  deb-tests:
    docker:
      - image: cimg/python:3.7
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - run: sudo apt-get update && sudo apt-get install -y make virtualenv enchant jq python3-dev build-essential rsync
      - checkout
      - setup_remote_docker
      - run:
          name: Test Debian package build
          command: |
            make ci-deb-tests
```

So the dep is missing and it complains.

Options:
1. Use 3.8+ everywhere, or
2. Use 3.7 to run pip-compile somehow, so these deps still get pinned
